// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeBoozin.Data;

#nullable disable

namespace WeBoozin.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240425084331_DropTrackerTable")]
    partial class DropTrackerTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WeBoozin.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CartId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("WeBoozin.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("WeBoozin.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryImage = "/Photos/Vodka.webp",
                            CategoryName = "Vodka"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryImage = "/Photos/Tequila.webp",
                            CategoryName = "Tequila"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryImage = "/Photos/Beer.webp",
                            CategoryName = "Beer"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryImage = "/Photos/Whiskey.webp",
                            CategoryName = "Whiskey"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryImage = "/Photos/Gin.webp",
                            CategoryName = "Gin"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryImage = "/Photos/Rum.webp",
                            CategoryName = "Rum"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryImage = "/Photos/Liquor.webp",
                            CategoryName = "Liquor"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryImage = "/Photos/Wine.webp",
                            CategoryName = "Wine"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryImage = "/Photos/Champagne.webp",
                            CategoryName = "Champagne"
                        });
                });

            modelBuilder.Entity("WeBoozin.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WeBoozin.Models.OrderDetails", b =>
                {
                    b.Property<int>("OrderDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderDetailsId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailsId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("WeBoozin.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<double>("AlcoholContent")
                        .HasColumnType("double");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QuantityInMl")
                        .HasColumnType("int");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            AlcoholContent = 40.0,
                            CategoryId = 1,
                            Description = "Feel the purity of your soul through this wonder drink.",
                            Image = "/Photos/Vodka1.webp",
                            ProductName = "Purity of Soul",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 2,
                            AlcoholContent = 40.0,
                            CategoryId = 1,
                            Description = "Feel the fire in your heart with this vodka designed to lit your soul.",
                            Image = "/Photos/Vodka2.webp",
                            ProductName = "Fire in the Heart",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 3,
                            AlcoholContent = 40.0,
                            CategoryId = 1,
                            Description = "Feel the lightness in your soul with every sip of this vodka.",
                            Image = "/Photos/Vodka3.webp",
                            ProductName = "Lightness of Soul",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 4,
                            AlcoholContent = 40.0,
                            CategoryId = 1,
                            Description = "Feel the freedom of your mind through after the first sip of this vodka.",
                            Image = "/Photos/Vodka4.webp",
                            ProductName = "Freedom of Mind",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 5,
                            AlcoholContent = 40.0,
                            CategoryId = 1,
                            Description = "Feel the victory in your veins with this vodka.",
                            Image = "/Photos/Vodka5.webp",
                            ProductName = "Victorious",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 6,
                            AlcoholContent = 40.0,
                            CategoryId = 1,
                            Description = "Feel the strength in your veins with this vodka.",
                            Image = "/Photos/Vodka6.webp",
                            ProductName = "Russian Power",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 7,
                            AlcoholContent = 40.0,
                            CategoryId = 1,
                            Description = "Feel the glory like a Russian with this vodka.",
                            Image = "/Photos/Vodka7.webp",
                            ProductName = "Russian Glory",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 8,
                            AlcoholContent = 40.0,
                            CategoryId = 1,
                            Description = "Become an alpha of your pac after the first sip of this vodka.",
                            Image = "/Photos/Vodka8.webp",
                            ProductName = "Alpha Male",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 9,
                            AlcoholContent = 40.0,
                            CategoryId = 1,
                            Description = "Become an elite with this vodka.",
                            Image = "/Photos/Vodka9.webp",
                            ProductName = "World ELite",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 10,
                            AlcoholContent = 45.0,
                            CategoryId = 2,
                            Description = "Live through the fire of Latino culture.",
                            Image = "/Photos/Tequila1.webp",
                            ProductName = "Latino Fire",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 11,
                            AlcoholContent = 37.0,
                            CategoryId = 2,
                            Description = "Feel the pride of Mexico with this tequila.",
                            Image = "/Photos/Tequila2.webp",
                            ProductName = "Mexican Pride",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 12,
                            AlcoholContent = 40.0,
                            CategoryId = 2,
                            Description = "Experience the Mexican fiesta at your home.",
                            Image = "/Photos/Tequila3.webp",
                            ProductName = "Fiesta",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 13,
                            AlcoholContent = 42.0,
                            CategoryId = 2,
                            Description = "From the people. For the people. Live it.",
                            Image = "/Photos/Tequila4.webp",
                            ProductName = "Los Bandidos",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 14,
                            AlcoholContent = 45.0,
                            CategoryId = 2,
                            Description = "Show you have got what it takes to earn it.",
                            Image = "/Photos/Tequila5.webp",
                            ProductName = "Blood Money",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 15,
                            AlcoholContent = 45.0,
                            CategoryId = 2,
                            Description = "Celebrate the day of the dead with this tequila.",
                            Image = "/Photos/Tequila6.webp",
                            ProductName = "Dia de Muertos",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 16,
                            AlcoholContent = 38.0,
                            CategoryId = 2,
                            Description = "Feel like a boss of the table with this tequila.",
                            Image = "/Photos/Tequila7.webp",
                            ProductName = "El Patron",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 17,
                            AlcoholContent = 40.0,
                            CategoryId = 2,
                            Description = "Live through the Mexican night with this tequila.",
                            Image = "/Photos/Tequila8.webp",
                            ProductName = "Mexican Night",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 18,
                            AlcoholContent = 40.0,
                            CategoryId = 2,
                            Description = "Meet and greet the Mexican sunrise with this tequila.",
                            Image = "/Photos/Tequila9.webp",
                            ProductName = "Mexican Sunrise",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 19,
                            AlcoholContent = 8.5,
                            CategoryId = 3,
                            Description = "Feel the freshness of pine forest with this beer.",
                            Image = "/Photos/Beer1.webp",
                            ProductName = "Pine Forest",
                            QuantityInMl = 500,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 20,
                            AlcoholContent = 6.5,
                            CategoryId = 3,
                            Description = "Feel the breeze of Alps with this beer.",
                            Image = "/Photos/Beer2.webp",
                            ProductName = "Alpine Breeze",
                            QuantityInMl = 500,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 21,
                            AlcoholContent = 7.0,
                            CategoryId = 3,
                            Description = "Crafted with love and dedication by the Fine Brothers.",
                            Image = "/Photos/Beer3.webp",
                            ProductName = "Fine Brothers",
                            QuantityInMl = 500,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 22,
                            AlcoholContent = 5.5,
                            CategoryId = 3,
                            Description = "Brewed from the best golden wheat.",
                            Image = "/Photos/Beer4.webp",
                            ProductName = "Golden Wheat",
                            QuantityInMl = 500,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 23,
                            AlcoholContent = 7.5,
                            CategoryId = 3,
                            Description = "Fine dark beer for the bear in you.",
                            Image = "/Photos/Beer5.webp",
                            ProductName = "Bearish",
                            QuantityInMl = 500,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 24,
                            AlcoholContent = 6.0,
                            CategoryId = 3,
                            Description = "Brewed to be enjoyed with friends.",
                            Image = "/Photos/Beer6.webp",
                            ProductName = "Quality Time",
                            QuantityInMl = 500,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 25,
                            AlcoholContent = 8.6999999999999993,
                            CategoryId = 3,
                            Description = "Essential beer for every BBQ master.",
                            Image = "/Photos/Beer7.webp",
                            ProductName = "BBQ Master",
                            QuantityInMl = 500,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 26,
                            AlcoholContent = 6.7999999999999998,
                            CategoryId = 3,
                            Description = "Brewed in the traditional Bavarian style.",
                            Image = "/Photos/Beer8.webp",
                            ProductName = "Bavarian",
                            QuantityInMl = 500,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 27,
                            AlcoholContent = 7.7000000000000002,
                            CategoryId = 3,
                            Description = "Finest Dark beer from the Czech Republic.",
                            Image = "/Photos/Beer9.webp",
                            ProductName = "Czech Pride",
                            QuantityInMl = 500,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 28,
                            AlcoholContent = 40.0,
                            CategoryId = 4,
                            Description = "The choice of every gentleman.",
                            Image = "/Photos/Whiskey1.webp",
                            ProductName = "Gentleman's Choice",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 29,
                            AlcoholContent = 45.0,
                            CategoryId = 4,
                            Description = "Free the wolf inside you with this fine whiskey.",
                            Image = "/Photos/Whiskey2.webp",
                            ProductName = "Dark Wolf",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 30,
                            AlcoholContent = 40.0,
                            CategoryId = 4,
                            Description = "Feel the pride of Ireland with this whiskey.",
                            Image = "/Photos/Whiskey3.webp",
                            ProductName = "Irish Pride",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 31,
                            AlcoholContent = 38.0,
                            CategoryId = 4,
                            Description = "Crafted to unite the world.",
                            Image = "/Photos/Whiskey4.webp",
                            ProductName = "United Together",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 32,
                            AlcoholContent = 40.0,
                            CategoryId = 4,
                            Description = "Dive into the infinity with this whiskey.",
                            Image = "/Photos/Whiskey5.webp",
                            ProductName = "Infinity",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 33,
                            AlcoholContent = 42.0,
                            CategoryId = 4,
                            Description = "Symbolizes the good old times through its unique taste.",
                            Image = "/Photos/Whiskey6.webp",
                            ProductName = "Golden Age of Whiskey",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 34,
                            AlcoholContent = 43.0,
                            CategoryId = 4,
                            Description = "The choice of every royal family.",
                            Image = "/Photos/Whiskey7.webp",
                            ProductName = "Royal Choice",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 35,
                            AlcoholContent = 40.0,
                            CategoryId = 4,
                            Description = "Crafted to be enjoyed in the dark night.",
                            Image = "/Photos/Whiskey8.webp",
                            ProductName = "Dark Night",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 36,
                            AlcoholContent = 38.0,
                            CategoryId = 4,
                            Description = "Become the shooter you always wanted to be.",
                            Image = "/Photos/Whiskey9.webp",
                            ProductName = "Shooter's",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 37,
                            AlcoholContent = 40.0,
                            CategoryId = 5,
                            Description = "Feel the freshness of morning dew with this gin.",
                            Image = "/Photos/Gin1.webp",
                            ProductName = "Morning Dew",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 38,
                            AlcoholContent = 35.0,
                            CategoryId = 5,
                            Description = "Feel the atmosphere of sunset on the beach with this gin.",
                            Image = "/Photos/Gin2.webp",
                            ProductName = "Sunset on the Beach",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 39,
                            AlcoholContent = 43.0,
                            CategoryId = 5,
                            Description = "Feel the chill of ice bath with this gin.",
                            Image = "/Photos/Gin3.webp",
                            ProductName = "Ice Bath",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 40,
                            AlcoholContent = 40.0,
                            CategoryId = 5,
                            Description = "For adventurous souls only.",
                            Image = "/Photos/Gin4.webp",
                            ProductName = "Alligator",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 41,
                            AlcoholContent = 38.0,
                            CategoryId = 5,
                            Description = "Brings calmness and tranquility to your soul.",
                            Image = "/Photos/Gin5.webp",
                            ProductName = "Serenity",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 42,
                            AlcoholContent = 45.0,
                            CategoryId = 5,
                            Description = "Adrenaline rush in a bottle.",
                            Image = "/Photos/Gin6.webp",
                            ProductName = "Fury",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 43,
                            AlcoholContent = 40.0,
                            CategoryId = 5,
                            Description = "Feel the British punch with this gin.",
                            Image = "/Photos/Gin7.webp",
                            ProductName = "Britih Punch",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 44,
                            AlcoholContent = 45.0,
                            CategoryId = 5,
                            Description = "Feel the heat of Texas with this gin.",
                            Image = "/Photos/Gin8.webp",
                            ProductName = "Texas Heat",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 45,
                            AlcoholContent = 40.0,
                            CategoryId = 5,
                            Description = "Answer the call of nature and live peacefully with your inner self.",
                            Image = "/Photos/Gin9.webp",
                            ProductName = "Nature Calls",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 46,
                            AlcoholContent = 40.0,
                            CategoryId = 6,
                            Description = "The choice of every pirate.",
                            Image = "/Photos/Rum1.webp",
                            ProductName = "Pirate's Choice",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 47,
                            AlcoholContent = 42.0,
                            CategoryId = 6,
                            Description = "Feel ocean's power with every sip.",
                            Image = "/Photos/Rum2.webp",
                            ProductName = "Sea Storm",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 48,
                            AlcoholContent = 38.0,
                            CategoryId = 6,
                            Description = "Feel the tranquility of Caribbean night with this rum.",
                            Image = "/Photos/Rum3.webp",
                            ProductName = "Caribbean Night",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 49,
                            AlcoholContent = 40.0,
                            CategoryId = 6,
                            Description = "For true partygoers only.",
                            Image = "/Photos/Rum4.webp",
                            ProductName = "Partygoer",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 50,
                            AlcoholContent = 38.0,
                            CategoryId = 6,
                            Description = "Taste from a different galaxy.",
                            Image = "/Photos/Rum5.webp",
                            ProductName = "Stellar",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 51,
                            AlcoholContent = 40.0,
                            CategoryId = 6,
                            Description = "Feel the mesmerizing beauty of an eclipse with this rum.",
                            Image = "/Photos/Rum6.webp",
                            ProductName = "Eclipse",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 52,
                            AlcoholContent = 42.0,
                            CategoryId = 6,
                            Description = "For real explorers of the world.",
                            Image = "/Photos/Rum7.webp",
                            ProductName = "Voyager",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 53,
                            AlcoholContent = 40.0,
                            CategoryId = 6,
                            Description = "Become a dreamer with the first sip of this rum.",
                            Image = "/Photos/Rum8.webp",
                            ProductName = "Dreamer",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 54,
                            AlcoholContent = 38.0,
                            CategoryId = 6,
                            Description = "Feel the warmth and vitality with every sip.",
                            Image = "/Photos/Rum9.webp",
                            ProductName = "Sunny Way",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 55,
                            AlcoholContent = 35.0,
                            CategoryId = 7,
                            Description = "Live and enjoy through the Oriental night with this liquor.",
                            Image = "/Photos/Liquor1.webp",
                            ProductName = "Oriental Night",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 56,
                            AlcoholContent = 33.0,
                            CategoryId = 7,
                            Description = "Become the dancing star of the night with this liquor.",
                            Image = "/Photos/Liquor2.webp",
                            ProductName = "Dancing Star",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 57,
                            AlcoholContent = 30.0,
                            CategoryId = 7,
                            Description = "Taste the sophisticated sweetness of fruits.",
                            Image = "/Photos/Liquor3.webp",
                            ProductName = "Sweet Fruit",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 58,
                            AlcoholContent = 35.0,
                            CategoryId = 7,
                            Description = "Ignite the spark of passion inside you.",
                            Image = "/Photos/Liquor4.webp",
                            ProductName = "Passion",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 59,
                            AlcoholContent = 33.0,
                            CategoryId = 7,
                            Description = "Taste like a garden in full bloom.",
                            Image = "/Photos/Liquor5.webp",
                            ProductName = "Garden Bloom",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 60,
                            AlcoholContent = 33.0,
                            CategoryId = 7,
                            Description = "White as snow. Pure as a soul.",
                            Image = "/Photos/Liquor6.webp",
                            ProductName = "Albino",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 61,
                            AlcoholContent = 35.0,
                            CategoryId = 7,
                            Description = "For an extravagant soul ready to dive into the unknown.",
                            Image = "/Photos/Liquor7.webp",
                            ProductName = "Extravaganza",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 62,
                            AlcoholContent = 34.0,
                            CategoryId = 7,
                            Description = "The taste is as beautiful as the night sky.",
                            Image = "/Photos/Liquor8.webp",
                            ProductName = "Night Sky",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 63,
                            AlcoholContent = 35.0,
                            CategoryId = 7,
                            Description = "Tje choice of every champion.",
                            Image = "/Photos/Liquor9.webp",
                            ProductName = "Champ's",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 64,
                            AlcoholContent = 12.0,
                            CategoryId = 8,
                            Description = "Sophistication and unity.",
                            Image = "/Photos/Wine1.webp",
                            ProductName = "Trinity",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 65,
                            AlcoholContent = 12.5,
                            CategoryId = 8,
                            Description = "Feel the elegance and romance in every sip.",
                            Image = "/Photos/Wine2.webp",
                            ProductName = "Elegant Romance",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 66,
                            AlcoholContent = 13.300000000000001,
                            CategoryId = 8,
                            Description = "You won't be able to resist this wine.",
                            Image = "/Photos/Wine3.webp",
                            ProductName = "Red Temptation",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 67,
                            AlcoholContent = 11.5,
                            CategoryId = 8,
                            Description = "Overflowing with energy and freshness.",
                            Image = "/Photos/Wine4.webp",
                            ProductName = "White Energy",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 68,
                            AlcoholContent = 12.800000000000001,
                            CategoryId = 8,
                            Description = "Premium wine for the queen in you.",
                            Image = "/Photos/Wine5.webp",
                            ProductName = "Queen's Throne",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 69,
                            AlcoholContent = 13.0,
                            CategoryId = 8,
                            Description = "Feel the royalty with every bottle.",
                            Image = "/Photos/Wine6.webp",
                            ProductName = "Red Crown",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 70,
                            AlcoholContent = 11.9,
                            CategoryId = 8,
                            Description = "Purity and excellence in every glass",
                            Image = "/Photos/Wine7.webp",
                            ProductName = "White Rose",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 71,
                            AlcoholContent = 12.5,
                            CategoryId = 8,
                            Description = "Rare and precious like gold.",
                            Image = "/Photos/Wine8.webp",
                            ProductName = "Gold Rose",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 72,
                            AlcoholContent = 12.300000000000001,
                            CategoryId = 8,
                            Description = "Let's you crete the atmosphere to share with your loved ones.",
                            Image = "/Photos/Wine9.webp",
                            ProductName = "Cozy Night",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 73,
                            AlcoholContent = 12.5,
                            CategoryId = 9,
                            Description = "The choice of every royal family.",
                            Image = "/Photos/Champagne1.webp",
                            ProductName = "Royal Club",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 74,
                            AlcoholContent = 12.6,
                            CategoryId = 9,
                            Description = "Feel the rich taste of this champagne.",
                            Image = "/Photos/Champagne2.webp",
                            ProductName = "Rich",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 75,
                            AlcoholContent = 12.0,
                            CategoryId = 9,
                            Description = "Feel yourself like a Russian noble with this champagne.",
                            Image = "/Photos/Champagne3.webp",
                            ProductName = "Russian Nobility",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 76,
                            AlcoholContent = 13.800000000000001,
                            CategoryId = 9,
                            Description = "Stong and powerful like a dynasty.",
                            Image = "/Photos/Champagne4.webp",
                            ProductName = "Dynasty",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 77,
                            AlcoholContent = 12.5,
                            CategoryId = 9,
                            Description = "Invoke the desire for something you deserve.",
                            Image = "/Photos/Champagne5.webp",
                            ProductName = "Desire",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 78,
                            AlcoholContent = 14.0,
                            CategoryId = 9,
                            Description = "Rare and glorious like a diamond.",
                            Image = "/Photos/Champagne6.webp",
                            ProductName = "Rare Glory",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 79,
                            AlcoholContent = 13.699999999999999,
                            CategoryId = 9,
                            Description = "Fine Italian champagne for the connoisseurs.",
                            Image = "/Photos/Champagne7.webp",
                            ProductName = "Apennini",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 80,
                            AlcoholContent = 14.5,
                            CategoryId = 9,
                            Description = "The pleasure you won't be able to resist.",
                            Image = "/Photos/Champagne8.webp",
                            ProductName = "Guilty Pleasure",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 81,
                            AlcoholContent = 13.4,
                            CategoryId = 9,
                            Description = "Makes you enjoy every sip like it was your last romance",
                            Image = "/Photos/Champagne9.webp",
                            ProductName = "Last Romance",
                            QuantityInMl = 750,
                            QuantityInStock = 50
                        });
                });

            modelBuilder.Entity("WeBoozin.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WeBoozin.Models.Cart", b =>
                {
                    b.HasOne("WeBoozin.Models.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("WeBoozin.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeBoozin.Models.CartItem", b =>
                {
                    b.HasOne("WeBoozin.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeBoozin.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WeBoozin.Models.Order", b =>
                {
                    b.HasOne("WeBoozin.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeBoozin.Models.OrderDetails", b =>
                {
                    b.HasOne("WeBoozin.Models.Order", "Orders")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeBoozin.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WeBoozin.Models.Product", b =>
                {
                    b.HasOne("WeBoozin.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WeBoozin.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("WeBoozin.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WeBoozin.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("WeBoozin.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("WeBoozin.Models.User", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
